const express=require("express")
const hotelRoute=express.Router()
const {verifyAdmin}=require("../../utils/verify")
const {httpGetCountByType,httpGetCountByCity,httpGetHotelRooms,httpGetAll,httpGetAllHotels, httpGetHotelById,httpAddNewHotel,httpUpdateHotel,httpDeleteHotel}=require("./hotels")
hotelRoute.get("/",httpGetAllHotels)
hotelRoute.get("/all",httpGetAll)
hotelRoute.get("/find/:id",httpGetHotelById)
hotelRoute.get("/countByCity",httpGetCountByCity)
hotelRoute.get("/countByType",httpGetCountByType)
hotelRoute.get("/room/:id",httpGetHotelRooms)
hotelRoute.post("/",httpAddNewHotel)
hotelRoute.put("/",httpUpdateHotel)
hotelRoute.delete("/:id",verifyAdmin,httpDeleteHotel)
module.exports=hotelRoute